image:
  tag: "466"
server:
  workers: 6
coordinator:
  jvm:
    maxHeapSize: "8G"
worker:
  jvm:
    maxHeapSize: "24G"
  config:
    memory:
      heapHeadroomPerNode: ""
    query:
      maxMemoryPerNode: "12GB"
catalogs:
  iceberg: |-
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.hive-system.svc:9083
    iceberg.catalog.type=hive_metastore
    fs.native-s3.enabled=true
    s3.region=us-east-1
    s3.path-style-access=true
    s3.endpoint=http://10.x.x.x
    s3.aws-access-key=PcsfafI
    s3.aws-secret-key=AfffPEFM
  delta: |-
    connector.name=delta_lake
    hive.metastore.uri=thrift://hive-metastore.hive-system.svc:9083
    fs.native-s3.enabled=true
    s3.region=us-east-1
    s3.path-style-access=true
    s3.endpoint=http://10.x.x.x
    s3.aws-access-key=PSsSAZRsgsHOI
    s3.aws-secret-key=A1sdFFFFRRRRR
