apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-hive-cfg
  namespace: analytics
data:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.default.name</name>
        <value>s3a://${FB_BUCKET}/</value>
      </property>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>false</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>${S3_ENDPOINT}</value>
      </property>
      <property>
        <name>fs.s3a.fast.upload</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.access.key</name>
        <value>${S3_ACCESS_KEY}</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>${S3_SECRET_KEY}</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
      </property>
    </configuration>