apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  selector:
    matchLabels:
      app: hive-metastore
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: unnikrishnan262/hive:latest
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: updated-hive-config
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml

            - name: updated-hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
          command: ["/opt/hive/bin/hive"]
          args: ["--service", "metastore"]
          imagePullPolicy: Always

      initContainers:
        - name: init-container-hadoop
          image: bhgedigital/envsubst
          volumeMounts:
            - name: hadoop-hive-cfg
              mountPath: /config/core-site.xml
              subPath: core-site.xml
            - name: updated-hadoop-config
              mountPath: /updated-hadoop-config
          command: ["/bin/sh", "-c"]
          args:
          - |
            envsubst < /config/core-site.xml > /updated-hadoop-config/core-site.xml
      
          env:
          - name: S3_ENDPOINT
            value: "10.21.236.205"
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: S3_SECRET_KEY
      
        - name: init-container-hive
          image: bhgedigital/envsubst
          volumeMounts:
            - name: hive-cfg-vol
              mountPath: /config/
            - name: updated-hive-config
              mountPath: /updated-hive-config
          command: ["/bin/sh", "-c"]
          args:
          - |
            envsubst < /config/hive-site.xml > /updated-hive-config/hive-site.xml
      
          env:
          - name: HIVE_POSTGRES_URL
            value: "jdbc:postgresql://hivems-primary.analytics.svc:5432"
          - name: HIVE_POSTGRES_USERNAME
            value: "hiveuser"
          - name: schema_name
            value: "metastore"
          - name: HIVE_S3_WAREHOUSE_BUCKET
            value: "s3a://iceberg/hive/warehouse"
          - name: HIVE_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: HIVE_POSTGRES_PASSWORD
      volumes:
        - name: hadoop-hive-cfg
          configMap:
            name: hadoop-hive-cfg
        - name: hive-cfg-vol
          configMap:
            name: hive-cfg
        - name: updated-hadoop-config
          emptyDir: {}
        - name: updated-hive-config
          emptyDir: {}
      



